### ISSUE TITLE
About Affine Function 

### ISSUE THREAD

**Issue by BassyKuo** [jwyang/lr-gan.pytorch#5]
Thank you for your great work.
I am studying your code recently. However, I do not touch any pytorch before so that cannot figure out how the affine function(in modules/gridgen.py & functions/gridgen.py) works.
Could you explain the meaning of  variable 'grid', 'grad_output', 'grad_input' respectly? Or show the workflow of AffineGridGen how to do. It will be very helpful for me to understand the full operating workflow in LR-GAN. Thank you so much.

**Comment by jwyang** [comment]
Hi,

The AffineGridGen is aimed to generate sampling grid given a affine transformation matrix (2x3). Given the generated grid, we then perform bilinear sample from the input feature maps. In LR-GAN, we will sample from the generated foreground and mask, and then put them on top of background based on alpha blending. Hope this explain clearly.

BTW, if you are confused by a specific number of lines in the code, you can post them here. This will help me to know what you do not understand exactly.
